name: map_themes
description: "A flutter plugin providing customizable Map themes."
version: 0.0.3+3
homepage: https://github.com/Captured-Heart/map_themes
issue_tracker: https://github.com/Captured-Heart/map_themes/issues
# documentation: add my medium link later
screenshots:
  - description: "Example of [Dark] map theme applied on Google Maps."
    path: example/screenshots/dark.png
  - description: "Example of [Dark] map theme [with Selector] on Google Maps."
    path: example/screenshots/dark1.png
  - description: "Example of [Night] map theme applied on Google Maps."
    path: example/screenshots/night.png
  - description: "Example of [Night] map theme [with Selector] on Google Maps."
    path: example/screenshots/night1.png
  - description: "Example of [Retro] map theme applied on Google Maps."
    path: example/screenshots/retro.png
  - description: "Example of [Retro] map theme [with Selector] on Google Maps."
    path: example/screenshots/retro1.png
  - description: "Example of [Night Blue] map theme applied on Google Maps."
    path: example/screenshots/nightBlue.png
  - description: "Example of [Original] map theme applied on Google Maps."
    path: example/screenshots/original.png

topics:
  - map
  - themes
  - flutter
  - google-maps-flutter

false_secrets:
  - /example/ios/Runner/AppDelegate.swift
  - "YOUR_GOOGLE_MAPS_API_KEY_HERE"

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.12
  mocktail: ^1.0.4
  shared_preferences_platform_interface: ^2.4.1
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    - lib/assets/
    - lib/assets/dark.json
    - lib/assets/night.json
    - lib/assets/night_blue.json
    - lib/assets/retro.json
